site_name: WireMock gRPC Extension Documentation
site_description: WireMock gRPC Extension Documentation.

site_url: https://wiremock.org/docs/grpc-extension/

copyright: Copyright &copy; 2024 - WireMock Contributors
docs_dir: .
repo_url: https://github.com/wiremock/wiremock-grpc-extension
repo_name: WireMock gRPC Extension

edit_uri: edit/main/

use_directory_urls: false

nav:
  - Overview: index.md